---
title: "223 - Week 2 Discussion"
author: "Garrett Craig"
date: "`r Sys.Date()`"
format:
  html:
    toc: true
    toc-location: left
    toc-depth: 3
    number_sections: true
    code-fold: true
    code-tools: true
    code-summary: "Show Code"
    embed-resources: true
    theme: darkly
execute:
  eval: true
  cache: true
  message: false
  warning: false
editor: 
  markdown: 
    wrap: sentence 
---

# 1. Get Started

## Load Libraries

```{r}
library(tidyverse)
library(sf)
library(tmap)
library(here)
```

```{r}
# load data in here, week2, discussion,data
aves <- read_csv(here("week2", "discussion", "data", "dataves.csv"))

#load Colombia shapefile
col <- st_read(here("week2", "discussion", "data", "Colombia","Colombia.shp"))

#load RDLINE_colombia shapefile
roads <- st_read(here("week2", "discussion", "data", "RDLINE_colombia","RDLINE_colombia.shp"))
```

```{r}
#se rename() to rename the columns decimal_longitude and decimal_latitude to long and lat in the bird observation dataset Use st_as_sf() to convert the bird observation dataset into an sf object

aves <- aves %>%
  rename(long = decimal_longitude, lat = decimal_latitude) %>%
  st_as_sf(coords = c("long", "lat"), crs = 4326)
```

# 2. View class and geometry type

```{r}
#check class of all vector objects
class(aves)
class(col)
class(roads)

#Use st_geometry_type() to peak at the geometry type
unique(st_geometry_type(aves))
unique(st_geometry_type(col))
unique(st_geometry_type(roads))
```

# 3. Select a macro ecoregion of interest

```{r}
#Use filter() to select a macro region of interest from N1_MacroBi in Colombia’s ecoregions dataset Plot the subset using tmap
col_andean <- col %>%
  # Set categorical "levels" in attribute N1_MacroBi (subregions of Colombia)
  mutate(N1_MacroBi = as.factor(N1_MacroBi)) |>
  # Subset to Andean region of Colombia
  filter(N1_MacroBi == "Andean")

tm_shape(col_andean) +
  tm_polygons() +
  tm_layout(main.title = "Andean Region of Colombia")
```

# 4. Play with coordinate reference system (CRS)

```{r}
# View CRS of each object
st_crs(col)
st_crs(roads)
st_crs(aves)
```

```{r}
# View units of each object CRS 
st_crs(col)$units
st_crs(roads)$units
st_crs(aves)$units
```

```{r}
# Use map() to unlist/extract
# Extract the longitude and latitude from the geometry column and use st_drop_geometry()
aves_df_purrr <- aves |> 
mutate(lon = unlist(purrr::map(aves$geometry, 1)), # longitude = first component (x)
         lat = unlist(purrr::map(aves$geometry, 2))) |> # latitude = second component (y)
  st_drop_geometry() # Remove geometry column now that it's redundant

# Use st_coordinates() to extract/assign
aves_df_st_coords <- aves |> 
  mutate(lon = st_coordinates(aves)[,1], # longitude = first column (x)
         lat = st_coordinates(aves)[,2]) |> # latitude = second column (y)
  st_drop_geometry() # Remove geometry column now that it's redundant
```

```{r}
#Convert to an sf object with st_as_sf()
aves_df_purrr <- aves |>
  st_as_sf(coords = c("lon", "lat"), crs = 4326)
```

# 5. Make a map
```{r}
#Check that the CRS of the ecoregions and roads datasets match Transform CRS of the bird observations dataset using st_transform() to match with the other datasets Use tmap to plot the ecoregions, roads, and bird observations together. include a compass and scale bar

st_crs(col)
st_crs(roads)
aves <- st_transform(aves, st_crs(col))

tm_shape(col) +
  tm_polygons() +
  tm_shape(roads) +
  tm_lines(col = "blue") +
  tm_shape(aves) +
  tm_dots(col = "red", size = 0.1) +
  tm_layout(main.title = "Bird Observations in Colombia")

```


